call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'kien/ctrlp.vim'
Plug 'sjl/badwolf'
Plug 'vim-airline/vim-airline'
Plug 'smerrill/vcl-vim-plugin'
Plug 'editorconfig/editorconfig-vim'
Plug 'justinmk/vim-syntax-extra'
Plug 'Chiel92/vim-autoformat'
Plug 'arcticicestudio/nord-vim', { 'branch': 'main' }
Plug 'hashivim/vim-terraform'
call plug#end()
set tabstop=4
set shiftwidth=4
set number
set mouse=a
set ttymouse=xterm2
set report=0
set list
set listchars=tab:→\ ,space:·,nbsp:␣,trail:•,precedes:«,extends:»
colorscheme nord
map <F2> :NERDTreeToggle<CR>
map <F12> :YcmCompleter GoTo<CR>
let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist)|(\.(swp|ico|git|svn))$'
let g:ctrlp_show_hidden = 1
let g:clang_format#auto_format = 1
let g:ycm_max_diagnostics_to_display = 500
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
au BufWrite * :Autoformat
